/* This file was automatically generated by pyNLControl.*/


#include "EKF_Func.h"

void EKF_Func_Call_Func(casadi_real *u, casadi_real *y, casadi_real *xhatp, casadi_real *Pkp, casadi_real *Q11, casadi_real *Q22, casadi_real *Q33, casadi_real *R, casadi_real *xhat,  casadi_real *Phat );