/* This file was automatically generated by pyNLControl.*/


#include "EKF_Func.h"
#include "EKF_Func_Call.h"

void EKF_Func_Call_Func(casadi_real *u, casadi_real *y, casadi_real *xhatp, casadi_real *Pkp, casadi_real *Q11, casadi_real *Q22, casadi_real *Q33, casadi_real *R, casadi_real *xhat,  casadi_real *Phat )
{
    int i;

    const casadi_real *arg[8];
    casadi_real *res[2];
    casadi_int iw[0];
    casadi_real w[30];

    
    
    
    
    arg[0] = w + 0;
    
    
    arg[1] = w + 1;
    
    
    arg[2] = w + 2;
    
    
    arg[3] = w + 5;
    
    
    arg[4] = w + 14;
    
    
    arg[5] = w + 15;
    
    
    arg[6] = w + 16;
    
    
    arg[7] = w + 17;
    
    
    
    
    
    
    res[0] = w + 18;
    
    
    res[1] = w + 21;
    
    
    
    
    
    for (i = 0; i < 1; i++)
        w[i] = u[i-0];
    
    
    for (i = 1; i < 2; i++)
        w[i] = y[i-1];
    
    
    for (i = 2; i < 5; i++)
        w[i] = xhatp[i-2];
    
    
    for (i = 5; i < 14; i++)
        w[i] = Pkp[i-5];
    
    
    for (i = 14; i < 15; i++)
        w[i] = Q11[i-14];
    
    
    for (i = 15; i < 16; i++)
        w[i] = Q22[i-15];
    
    
    for (i = 16; i < 17; i++)
        w[i] = Q33[i-16];
    
    
    for (i = 17; i < 18; i++)
        w[i] = R[i-17];
    
    
    EKF_Func (arg, res, iw, w + 30, 0);
    
    
    
    for (i = 18; i < 21; i++)
        xhat[i-18] = w[i];
    
    
    for (i = 21; i < 30; i++)
        Phat[i-21] = w[i];
    
    
}